# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
solc_version = "0.8.27"
optimizer_runs = 222
remappings = [
	'forge-std/=lib/forge-std/src/',
	'@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
	"@/=src/",
]
out = "build/out"
cache_path = "build/cache"
src = "src/contracts"
libs = ["lib"]
test = "src/test"

[fmt]
line_length = 110
bracket_spacing = false
number_underscore = "thousands"
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
tab_width = 4
